engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 70
  eslint:
    enabled: true

exclude_paths:
- ".nyc_output"
- "coverage"
- "node_modules"
- "test/"